# Generated by Django 5.1.5 on 2025-02-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='gestion.vente'),
        ),
    ]
